package graph;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.Scanner;
import java.util.TreeMap;
import java.util.TreeSet;

public class Synset {

    public TreeMap<Integer, TreeSet<String>> table = new TreeMap<>();
    int size = 0; // since dataset is consecutive, assume every add is +1 to the size
    // but size does not correspond to ids, should abolish

    /**
     * Create Synset object by reading data CSV from provided file path
     * I can't believe it. The test passed in two try, and the one failure was simply
     * a mistake somewhere else in the code.
     * @param
     * path to the CSV intended to read
     * @throws RuntimeException which is generated by IDE so not sure as why throws runtime
     * instead of FileNotFound. But works as intended because I don't really know how
     * it should behave if given a wrong path, should I give an empty synset? Maybe.
     */
    public Synset(String path) {
        File file = new File(path);
        try {
            Scanner read = new Scanner(file);
            while (read.hasNextLine()) {
                String line = read.nextLine();
                String[] tokens = line.split(",");
                String[] words = tokens[1].split(" ");
                for (int i = 0; i < words.length; i++) {
                    words[i] = words[i].replaceAll("_", " ");
                }
                this.addSynset(Integer.parseInt(tokens[0]), words);
            }
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
    }

    public Synset() {
        table = new TreeMap<>();
    }

    public void addSynset(Integer i, String... syns) {
        if (syns == null) return;
//        if (table.containsKey(i)) table.get(i).addAll(List.of(syns)); // under same index
        // actually this whole line is unnecessary, cuz synset dataset is single line
        // but good idea as a api
        table.put(i, new TreeSet<>(List.of(syns)));
        size++;
    }

    public TreeSet<String> get(Integer i) {
        return table.get(i) == null ? new TreeSet<>() : table.get(i);
    }

    public TreeSet<Integer> getIndices(String word) {
        if (word == null) return new TreeSet<>();
        TreeSet<Integer> indices = new TreeSet<>();
        for (Integer i : table.keySet()) {
            if (table.get(i).contains(word)) indices.add(i);
        }
        return indices;
    }
}
